package music.entity;
// Generated Oct 10, 2013 1:36:35 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.GeneratedValue;
import javax.persistence.Id;




/**
 * Library generated by hbm2java
 */
public class Library  implements java.io.Serializable {

     @Id @GeneratedValue 
     private int id;

    public Library() {
    }

    public Library(int id) {
       this.id = id;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }




}


