package music.entity;
// Generated Oct 10, 2013 1:36:35 PM by Hibernate Tools 3.2.1.GA

import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;




/**
 * Library generated by hbm2java
 */
public class Library  implements java.io.Serializable {

     @Id @GeneratedValue 
     private int id;
     private List <Song> songs;

    public Library() {
    }

    public Library(int id) {
       this.id = id;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @OneToMany(targetEntity=Song.class, mappedBy="library", cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    public List<Song> getSongs() {
        return songs;
    }
    
    public void setSongs(List<Song> songs){
        this.songs = songs;
    }




}


