package music.entity;
// Generated Oct 10, 2013 1:36:35 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.GeneratedValue;
import javax.persistence.Id;




/**
 * Playlist generated by hbm2java
 */
public class Playlist  implements java.io.Serializable {

     @Id @GeneratedValue 
     private int id;
     private String name;

    public Playlist() {
    }

	
    public Playlist(int id) {
        this.id = id;
    }
    public Playlist(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


