package music.entity;
// Generated Oct 10, 2013 1:36:35 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * Song generated by hbm2java
 */
public class Song  implements java.io.Serializable {

     @Id @GeneratedValue 
     private int id;
     private String artist;
     private String title;
     private BigDecimal duration;
     private String filepath;
     private Integer playlistid;
     private Integer libraryid;
     private Library library;
     private Playlist playlist;

    public Song() {
    }

	
    public Song(int id) {
        this.id = id;
    }
    public Song(int id, String artist, String title, BigDecimal duration, String filepath, Integer playlistid, Integer libraryid) {
       this.id = id;
       this.artist = artist;
       this.title = title;
       this.duration = duration;
       this.filepath = filepath;
       this.playlistid = playlistid;
       this.libraryid = libraryid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getArtist() {
        return this.artist;
    }
    
    public void setArtist(String artist) {
        this.artist = artist;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public BigDecimal getDuration() {
        return this.duration;
    }
    
    public void setDuration(BigDecimal duration) {
        this.duration = duration;
    }
    public String getFilepath() {
        return this.filepath;
    }
    
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }
    public Integer getPlaylistid() {
        return this.playlistid;
    }
    
    public void setPlaylistid(Integer playlistid) {
        this.playlistid = playlistid;
    }
    public Integer getLibraryid() {
        return this.libraryid;
    }
    
    public void setLibraryid(Integer libraryid) {
        this.libraryid = libraryid;
    }
    
    @ManyToOne
    @JoinColumn(name="library_id")
    public Library getLibrary(Library library){
        return library;
    }

    public void setLibrary(Library library){
        this.library = library;
    }
    
    @ManyToOne
    @JoinColumn(name="playlist_id")
    public Playlist getPlaylist(Playlist playlist){
        return playlist;
    }

    public void setPlaylist(Playlist playlist){
        this.playlist = playlist;
    }



}


