package music.entity;
// Generated Oct 10, 2013 1:36:35 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.GeneratedValue;
import javax.persistence.Id;




/**
 * Useraccount generated by hbm2java
 */
public class Useraccount  implements java.io.Serializable {

     @Id @GeneratedValue 
     private int id;
    
     private String username;
     private String password;
     private String email;

    public Useraccount() {
    }

	
    public Useraccount(int id) {
        this.id = id;
    }
    public Useraccount(int id, String username, String password, String email) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.email = email;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


