package musicdata.entity;
// Generated Oct 3, 2013 4:36:56 PM by Hibernate Tools 3.2.1.GA



/**
 * Library generated by hbm2java
 */
public class Library  implements java.io.Serializable {


     private int id;

    public Library() {
    }

    public Library(int id) {
       this.id = id;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }




}


